-- CreateTable
CREATE TABLE `PHANCONGGIANGDAY` (
    `MaHK` VARCHAR(30) NOT NULL,
    `MaMH` VARCHAR(20) NOT NULL,
    `MaTK` INTEGER NOT NULL,
    `NgayPhanCong` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `PHANCONGGIANGDAY_MaTK_idx`(`MaTK`),
    PRIMARY KEY (`MaHK`, `MaMH`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PHANCONGGIANGDAY` ADD CONSTRAINT `PHANCONGGIANGDAY_MaHK_MaMH_fkey` FOREIGN KEY (`MaHK`, `MaMH`) REFERENCES `MONHOCMO`(`MaHK`, `MaMH`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHANCONGGIANGDAY` ADD CONSTRAINT `PHANCONGGIANGDAY_MaTK_fkey` FOREIGN KEY (`MaTK`) REFERENCES `TAIKHOAN`(`MaTK`) ON DELETE CASCADE ON UPDATE CASCADE;
