-- CreateTable
CREATE TABLE `KHOA` (
    `MaKhoa` VARCHAR(20) NOT NULL,
    `TenKhoa` VARCHAR(150) NOT NULL,

    PRIMARY KEY (`MaKhoa`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `NGANHHOC_MaKhoa_idx` ON `NGANHHOC`(`MaKhoa`);

-- AddForeignKey
ALTER TABLE `NGANHHOC` ADD CONSTRAINT `NGANHHOC_MaKhoa_fkey` FOREIGN KEY (`MaKhoa`) REFERENCES `KHOA`(`MaKhoa`) ON DELETE RESTRICT ON UPDATE CASCADE;
