import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
await prisma.phanCongGiangDay.deleteMany();
await prisma.giangVienProfile.deleteMany();
await prisma.phieuThu.deleteMany();
await prisma.phieuHocPhi.deleteMany();
await prisma.monHocMo.deleteMany();
await prisma.chuongTrinhHoc.deleteMany();
await prisma.monHoc.deleteMany();
await prisma.sinhVien.deleteMany();
await prisma.hocKy.deleteMany();
await prisma.taiKhoan.deleteMany();
await prisma.nganhHoc.deleteMany();
await prisma.loaiMon.deleteMany();
await prisma.doiTuongUuTien.deleteMany();
await prisma.queQuan.deleteMany();
await prisma.huyen.deleteMany();
await prisma.thamSo.deleteMany();
console.log('✓ Đã xóa toàn bộ dữ liệu cũ');
await prisma.$disconnect();
