-- CreateTable
CREATE TABLE `GIANGVIENPROFILE` (
    `MaTK` INTEGER NOT NULL,
    `NgaySinh` DATE NULL,
    `Khoa` VARCHAR(100) NULL,
    `BoMon` VARCHAR(100) NULL,
    `HocVi` VARCHAR(50) NULL,
    `HocHam` VARCHAR(50) NULL,
    `NamCongTac` INTEGER NULL,
    `QuaTrinhCT` TEXT NULL,
    `NgayCapNhat` DATETIME(3) NOT NULL,

    PRIMARY KEY (`MaTK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `GIANGVIENPROFILE` ADD CONSTRAINT `GIANGVIENPROFILE_MaTK_fkey` FOREIGN KEY (`MaTK`) REFERENCES `TAIKHOAN`(`MaTK`) ON DELETE CASCADE ON UPDATE CASCADE;
