-- CreateTable
CREATE TABLE `DONGIAHAN` (
    `MaDon` INTEGER NOT NULL AUTO_INCREMENT,
    `MaSV` VARCHAR(20) NOT NULL,
    `MaHK` VARCHAR(30) NOT NULL,
    `LyDo` TEXT NOT NULL,
    `TrangThai` VARCHAR(20) NOT NULL DEFAULT 'CHO_DUYET',
    `NgayNop` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `NgayXuLy` DATETIME(3) NULL,
    `NgayGiaHan` DATE NULL,
    `GhiChuAdmin` TEXT NULL,

    INDEX `DONGIAHAN_MaSV_MaHK_idx`(`MaSV`, `MaHK`),
    PRIMARY KEY (`MaDon`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `DONGIAHAN` ADD CONSTRAINT `DONGIAHAN_MaSV_fkey` FOREIGN KEY (`MaSV`) REFERENCES `SINHVIEN`(`MaSV`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DONGIAHAN` ADD CONSTRAINT `DONGIAHAN_MaHK_fkey` FOREIGN KEY (`MaHK`) REFERENCES `HOCKY`(`MaHK`) ON DELETE RESTRICT ON UPDATE CASCADE;
