-- AlterTable
ALTER TABLE `phieuhocphi` ADD COLUMN `HanDong` DATE NULL;

-- AlterTable
ALTER TABLE `taikhoan` ADD COLUMN `MustChangePassword` BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE `REFRESHTOKEN` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `MaTK` INTEGER NOT NULL,
    `Token` VARCHAR(512) NOT NULL,
    `ExpiresAt` DATETIME(3) NOT NULL,
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `REFRESHTOKEN_Token_key`(`Token`),
    INDEX `REFRESHTOKEN_MaTK_idx`(`MaTK`),
    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PASSWORDRESETTOKEN` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `MaTK` INTEGER NOT NULL,
    `Token` VARCHAR(512) NOT NULL,
    `ExpiresAt` DATETIME(3) NOT NULL,
    `UsedAt` DATETIME(3) NULL,
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `PASSWORDRESETTOKEN_Token_key`(`Token`),
    INDEX `PASSWORDRESETTOKEN_MaTK_idx`(`MaTK`),
    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AUDITLOG` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `MaTK` INTEGER NULL,
    `HanhDong` VARCHAR(50) NOT NULL,
    `DoiTuong` VARCHAR(50) NOT NULL,
    `DoiTuongId` VARCHAR(50) NULL,
    `MoTa` TEXT NULL,
    `IpAddress` VARCHAR(45) NULL,
    `ThoiGian` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `AUDITLOG_MaTK_idx`(`MaTK`),
    INDEX `AUDITLOG_ThoiGian_idx`(`ThoiGian`),
    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MONHOCYEUCAU` (
    `MaMH` VARCHAR(20) NOT NULL,
    `MaMHYeuCau` VARCHAR(20) NOT NULL,

    PRIMARY KEY (`MaMH`, `MaMHYeuCau`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `REFRESHTOKEN` ADD CONSTRAINT `REFRESHTOKEN_MaTK_fkey` FOREIGN KEY (`MaTK`) REFERENCES `TAIKHOAN`(`MaTK`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PASSWORDRESETTOKEN` ADD CONSTRAINT `PASSWORDRESETTOKEN_MaTK_fkey` FOREIGN KEY (`MaTK`) REFERENCES `TAIKHOAN`(`MaTK`) ON DELETE CASCADE ON UPDATE CASCADE;
