-- CreateTable
CREATE TABLE `TAIKHOAN` (
    `MaTK` INTEGER NOT NULL AUTO_INCREMENT,
    `Username` VARCHAR(50) NOT NULL,
    `PasswordHash` VARCHAR(255) NOT NULL,
    `HoTen` VARCHAR(100) NOT NULL,
    `Email` VARCHAR(100) NULL,
    `VaiTro` ENUM('ADMIN', 'PHONG_DAO_TAO', 'PHONG_TAI_CHINH', 'GIANG_VIEN', 'CO_VAN') NOT NULL,
    `TrangThai` ENUM('ACTIVE', 'DISABLED') NOT NULL DEFAULT 'ACTIVE',
    `NgayTao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `NgayCapNhat` DATETIME(3) NOT NULL,
    `LastLoginAt` DATETIME(3) NULL,

    UNIQUE INDEX `TAIKHOAN_Username_key`(`Username`),
    PRIMARY KEY (`MaTK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HUYEN` (
    `MaHuyen` VARCHAR(20) NOT NULL,
    `TenHuyen` VARCHAR(100) NOT NULL,
    `LaVungSauVungXa` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`MaHuyen`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `QUEQUAN` (
    `MaQueQuan` VARCHAR(20) NOT NULL,
    `TenTinh` VARCHAR(100) NOT NULL,
    `MaHuyen` VARCHAR(20) NOT NULL,

    INDEX `QUEQUAN_MaHuyen_idx`(`MaHuyen`),
    PRIMARY KEY (`MaQueQuan`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DOITUONGUUTIEN` (
    `MaDoiTuong` VARCHAR(20) NOT NULL,
    `TenDoiTuong` VARCHAR(100) NOT NULL,
    `TiLeGiamHocPhi` DECIMAL(4, 3) NOT NULL DEFAULT 0,

    PRIMARY KEY (`MaDoiTuong`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NGANHHOC` (
    `MaNganh` VARCHAR(20) NOT NULL,
    `TenNganh` VARCHAR(100) NOT NULL,
    `MaKhoa` VARCHAR(20) NOT NULL,

    PRIMARY KEY (`MaNganh`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LOAIMON` (
    `MaLoaiMon` VARCHAR(5) NOT NULL,
    `TenLoaiMon` VARCHAR(50) NOT NULL,
    `HeSoTinChi` DECIMAL(4, 2) NOT NULL DEFAULT 1.0,

    PRIMARY KEY (`MaLoaiMon`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SINHVIEN` (
    `MaSV` VARCHAR(20) NOT NULL,
    `TenSV` VARCHAR(100) NOT NULL,
    `NgaySinh` DATE NULL,
    `GioiTinh` ENUM('Nam', 'Nữ') NULL,
    `TenLop` VARCHAR(50) NULL,
    `Email` VARCHAR(100) NULL,
    `TrangThai` ENUM('DANG_HOC', 'BAO_LUU', 'TOT_NGHIEP') NOT NULL DEFAULT 'DANG_HOC',
    `MaQueQuan` VARCHAR(20) NULL,
    `MaDoiTuong` VARCHAR(20) NULL,
    `MaNganh` VARCHAR(20) NULL,
    `NgayTao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `NgayCapNhat` DATETIME(3) NOT NULL,

    INDEX `SINHVIEN_MaQueQuan_idx`(`MaQueQuan`),
    INDEX `SINHVIEN_MaDoiTuong_idx`(`MaDoiTuong`),
    INDEX `SINHVIEN_MaNganh_idx`(`MaNganh`),
    PRIMARY KEY (`MaSV`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MONHOC` (
    `MaMH` VARCHAR(20) NOT NULL,
    `TenMH` VARCHAR(150) NOT NULL,
    `MaLoaiMon` VARCHAR(5) NOT NULL,
    `SoTiet` INTEGER NOT NULL DEFAULT 45,
    `SoTinChi` INTEGER NOT NULL DEFAULT 3,
    `HocPhi` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    `HocKy` VARCHAR(20) NOT NULL,
    `TenKhoa` VARCHAR(100) NOT NULL,
    `SiSoToiDa` INTEGER NOT NULL DEFAULT 50,
    `SiSoHienTai` INTEGER NOT NULL DEFAULT 0,
    `NgayTao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `NgayCapNhat` DATETIME(3) NOT NULL,

    INDEX `MONHOC_MaLoaiMon_idx`(`MaLoaiMon`),
    PRIMARY KEY (`MaMH`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HOCKY` (
    `MaHK` VARCHAR(30) NOT NULL,
    `TenHK` VARCHAR(20) NOT NULL,
    `NamHoc` VARCHAR(20) NOT NULL,
    `LaHienTai` BOOLEAN NOT NULL DEFAULT false,
    `NgayBatDau` DATE NULL,
    `NgayKetThuc` DATE NULL,

    PRIMARY KEY (`MaHK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHUONGTRINHHOC` (
    `MaCTH` INTEGER NOT NULL AUTO_INCREMENT,
    `MaNganh` VARCHAR(20) NOT NULL,
    `MaMH` VARCHAR(20) NOT NULL,
    `HocKy` INTEGER NOT NULL,

    UNIQUE INDEX `CHUONGTRINHHOC_MaNganh_MaMH_key`(`MaNganh`, `MaMH`),
    PRIMARY KEY (`MaCTH`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MONHOCMO` (
    `MaHK` VARCHAR(30) NOT NULL,
    `MaMH` VARCHAR(20) NOT NULL,

    PRIMARY KEY (`MaHK`, `MaMH`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PHIEUHOCPHI` (
    `MaPhieu` VARCHAR(30) NOT NULL,
    `MaSV` VARCHAR(20) NOT NULL,
    `MaMH` VARCHAR(20) NOT NULL,
    `MaHK` VARCHAR(30) NOT NULL,
    `NgayLap` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `SoTienDangKy` DECIMAL(12, 0) NOT NULL,
    `SoTienPhaiDong` DECIMAL(12, 0) NOT NULL,

    INDEX `PHIEUHOCPHI_MaSV_idx`(`MaSV`),
    INDEX `PHIEUHOCPHI_MaHK_idx`(`MaHK`),
    INDEX `PHIEUHOCPHI_MaMH_idx`(`MaMH`),
    UNIQUE INDEX `PHIEUHOCPHI_MaSV_MaMH_MaHK_key`(`MaSV`, `MaMH`, `MaHK`),
    PRIMARY KEY (`MaPhieu`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PHIEUTHU` (
    `MaPhieuThu` VARCHAR(30) NOT NULL,
    `MaSV` VARCHAR(20) NOT NULL,
    `MaHK` VARCHAR(30) NOT NULL,
    `NgayThu` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `SoTienThu` DECIMAL(12, 0) NOT NULL,
    `GhiChu` VARCHAR(255) NULL,

    INDEX `PHIEUTHU_MaSV_MaHK_idx`(`MaSV`, `MaHK`),
    PRIMARY KEY (`MaPhieuThu`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `THAMSO` (
    `TenThamSo` VARCHAR(50) NOT NULL,
    `GiaTri` VARCHAR(255) NOT NULL,
    `KieuDuLieu` VARCHAR(20) NOT NULL DEFAULT 'number',
    `MoTa` VARCHAR(255) NULL,
    `NgayCapNhat` DATETIME(3) NOT NULL,

    PRIMARY KEY (`TenThamSo`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `QUEQUAN` ADD CONSTRAINT `QUEQUAN_MaHuyen_fkey` FOREIGN KEY (`MaHuyen`) REFERENCES `HUYEN`(`MaHuyen`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SINHVIEN` ADD CONSTRAINT `SINHVIEN_MaQueQuan_fkey` FOREIGN KEY (`MaQueQuan`) REFERENCES `QUEQUAN`(`MaQueQuan`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SINHVIEN` ADD CONSTRAINT `SINHVIEN_MaDoiTuong_fkey` FOREIGN KEY (`MaDoiTuong`) REFERENCES `DOITUONGUUTIEN`(`MaDoiTuong`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SINHVIEN` ADD CONSTRAINT `SINHVIEN_MaNganh_fkey` FOREIGN KEY (`MaNganh`) REFERENCES `NGANHHOC`(`MaNganh`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MONHOC` ADD CONSTRAINT `MONHOC_MaLoaiMon_fkey` FOREIGN KEY (`MaLoaiMon`) REFERENCES `LOAIMON`(`MaLoaiMon`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHUONGTRINHHOC` ADD CONSTRAINT `CHUONGTRINHHOC_MaNganh_fkey` FOREIGN KEY (`MaNganh`) REFERENCES `NGANHHOC`(`MaNganh`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHUONGTRINHHOC` ADD CONSTRAINT `CHUONGTRINHHOC_MaMH_fkey` FOREIGN KEY (`MaMH`) REFERENCES `MONHOC`(`MaMH`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MONHOCMO` ADD CONSTRAINT `MONHOCMO_MaHK_fkey` FOREIGN KEY (`MaHK`) REFERENCES `HOCKY`(`MaHK`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MONHOCMO` ADD CONSTRAINT `MONHOCMO_MaMH_fkey` FOREIGN KEY (`MaMH`) REFERENCES `MONHOC`(`MaMH`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHIEUHOCPHI` ADD CONSTRAINT `PHIEUHOCPHI_MaSV_fkey` FOREIGN KEY (`MaSV`) REFERENCES `SINHVIEN`(`MaSV`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHIEUHOCPHI` ADD CONSTRAINT `PHIEUHOCPHI_MaMH_fkey` FOREIGN KEY (`MaMH`) REFERENCES `MONHOC`(`MaMH`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHIEUHOCPHI` ADD CONSTRAINT `PHIEUHOCPHI_MaHK_fkey` FOREIGN KEY (`MaHK`) REFERENCES `HOCKY`(`MaHK`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHIEUTHU` ADD CONSTRAINT `PHIEUTHU_MaSV_fkey` FOREIGN KEY (`MaSV`) REFERENCES `SINHVIEN`(`MaSV`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHIEUTHU` ADD CONSTRAINT `PHIEUTHU_MaHK_fkey` FOREIGN KEY (`MaHK`) REFERENCES `HOCKY`(`MaHK`) ON DELETE RESTRICT ON UPDATE CASCADE;
